#This is a testing workflow designed just for development
#of the primary Action.

name: test
on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: ./
        with:
          repo: 'CMakePP/CMakeTest'
          ssh-key: ${{ secrets.SSH_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
